#baseURL = "https://codingclub.vietkidsnz.org/"
baseURL = ""
languageCode = "en"
title = "CodingClub-VietKidsNZ"

theme = "darkhorse"

enableemoji = true

[markup]
    [markup.goldmark.renderer]
        unsafe = true

[params]
    logo = "/images/coding-club-logo.png"
    background = "darkslategray"
    linkColor = "seagreen"
    darkLinkColor = "darkseagreen"
    dark404Button = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[menu]
    [[menu.main]]
        identifier = "home"
        pre = "<i class='fas fa-home'></i>"
        url = "/"
        name = "Home"
        weight = 1

    [[menu.main]]
        identifier = "projects"
        pre = "<i class='fas fa-laptop-code'></i>"
        url = "/projects/"
        name = "Projects"
        weight = 2


    [[menu.main]]
        identifier = "tutorials"
        url = "/tutorials/"
        name = "Tutorials"
        pre = "<i class='fas fa-book'></i>"
        weight = 3

    [[menu.main]]
        identifier = "posts"
        url = "/posts/"
        name = "Posts"
        pre = "<i class='far fa-newspaper'></i>"
        weight = 4

    [[menu.main]]
        identifier = "discuss"
        name = "Q&A"
        url = "/pages/discuss/"
        pre = "<i class='fas fa-comments'></i>"
        weight = 5

    [[menu.main]]
        identifier = "submit"
        name = "My Projects"
        url = "/pages/submit/"
        pre = "<i class='fas fa-file-code'></i>"
        weight = 6